// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2t7Rt3-lZi5orIQIcjF8zt9c0tjARc_8',
    appId: '1:309327872479:web:5d4c01a22d8c32fc74446a',
    messagingSenderId: '309327872479',
    projectId: 'khabar-790e3',
    authDomain: 'khabar-790e3.firebaseapp.com',
    storageBucket: 'khabar-790e3.firebasestorage.app',
    measurementId: 'G-21BQ1TQSRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt_on5SVB9LEWfVSfM6PJFywla9N2WoRA',
    appId: '1:309327872479:android:d1cec3378e3027d174446a',
    messagingSenderId: '309327872479',
    projectId: 'khabar-790e3',
    storageBucket: 'khabar-790e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqZvjeQYQTVgXEXhK5OxuXmC0ZZ7HsQjk',
    appId: '1:309327872479:ios:22ac37a38b6d16b674446a',
    messagingSenderId: '309327872479',
    projectId: 'khabar-790e3',
    storageBucket: 'khabar-790e3.firebasestorage.app',
    iosClientId: '309327872479-p4upnlima8o5g7u40geucumv71rqrnce.apps.googleusercontent.com',
    iosBundleId: 'com.example.khabar',
  );

}